services:
  client:
    image: djoufson/alice-client:latest
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_API_URL: http://server:8080
    ports:
      - 8000:3000
    networks:
      - alice

networks:
  alice:
    external: true
